import type { Metadata } from "next";
import ConnectionProvider from "@/components/providers/ConnectionProvider";
import WalletProvider from "@/components/providers/WalletProvider";;

import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <ConnectionProvider>
            <WalletProvider>
            {children}
            </WalletProvider>
          </ConnectionProvider>
      </body>
    </html>
  );
}
