import type { Metadata } from "next";
import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react'
import { clusterApiUrl } from "@solana/web3.js";

import { Inter } from "next/font/google";
import "./globals.css";
import { useMemo } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode}>) {
  
  const endpoint = clusterApiUrl("devnet");
  const wallets = useMemo(() => [], [])

  return (
    <html lang="en">
      <body className={inter.className}>
        <ConnectionProvider endpoint={endpoint}>
          <WalletProvider wallets={wallets}>
          {children}
          </WalletProvider>
        </ConnectionProvider>
      </body>
    </html>
  );
}
